baseurl = "https://lukewoodsmu.github.io/"
title = "Luke Wood"
theme = "aerial"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  name = "Luke Wood"
  about = 'Software Engineer'
  bg_scroll = ""
  logo = "fa-tree"
  copyright = "Luke Wood"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/lukewoodsmu"

[[params.social]]
  medium = "Resume"
  icon = "file"
  link = "/Resume.pdf"
