baseURL = "https://LukeWood.dev/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Luke Wood"
theme = "hermit"
# enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
# hasCJKLanguage = true  # If Chinese/Japanese/Korean is your main content language, enable this to make wordCount works right.
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
googleAnalytics = "UA-139935010-1"

[author]
  name = "LukeWood.dev"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  commento = true

  # Metadata mostly used in document's head
  description = "LukeWood.dev is my personal tech blog."
  images = ["img/backgrounds/IMG_8532-EFFECTS.jpg", "img/backgrounds/IMG_8771-EFFECTS.jpg", "img/backgrounds/hawaii_1.jpg"]
  themeColor = "#494f5c"

  homeSubtitle = "SURF | SKI | SWE"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  bgImg = "img/backgrounds/IMG_8532-EFFECTS.jpg"  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/username/repository/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  # Add custom css
  customCSS = ["css/figures.css", "css/gist.css", "css/headers.css", "css/commento.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "github"
    url = "https://github.com/LukeWood"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/luke-wood-886634102/"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "about-me/"
    weight = 20
