baseURL = "https://LukeWood.dev/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "LukeWood.dev"
copyright = "Copyright Luke Wood 2019" # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
googleAnalytics = "UA-139935010-1"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[params]
  [[params.social]]
    name = "github"
    url = "https://github.com/LukeWood"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/luke-wood-886634102/"
