baseURL = "https://LukeWood.dev/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "LukeWood.dev"
copyright = "Copyright Luke Wood 2019"

enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
googleAnalytics = "UA-139935010-1"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true
[authors]
  name = "Luke Wood"

[params]

  images = [
    "https://LukeWood.dev/img/index/ballpark.jpg"
  ]
  locale = "en_US"
  themeColor = "#82b1ff"
  description = "LukeWood.dev is my personal website.  It serves as a tech blog, photo gallery, code showcase, and project portfolio."

  [[params.social]]
    name = "github"
    url = "https://github.com/LukeWood"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/luke-wood-886634102/"

[taxonomies]
  post = "posts"
  snippet = "snippets"
  project = "projects"
  photo = "photos"
