baseurl = "https://lukewoodsmu.github.io/"
title = "Dimension"
theme = "base16"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Luke Wood"
  description = '<!--[-->Software Engineer<!--]--><br />'
  logo = "fa-tree"
  copyright = "Luke Wood"
