baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "LukeWood.dev"
copyright = "Copyright Luke Wood 2019"
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
googleAnalytics = "UA-139935010-1"
theme = "birch"

[authors]
  name = "Luke Wood"

[params]
  locale = "en_US"
  themeColor = "#82b1ff"
  description = "LukeWood.dev is my personal website.  It serves as a tech blog, code showcase, and project portfolio."

  [[params.social]]
    name = "github"
    url = "https://github.com/LukeWood"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/luke-wood-886634102/"

  [[params.social]]
    name = "email"
    url = "mailto:me@lukewood.dev"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 0
  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 1

  #[[menu.main]]
  #  name = "Snippets"
  #  url = "/snippets"
  #[[menu.main]]
  #  name = "Projects"
  #  url = "/projects"
  #[[menu.main]]
  #  name = "Photos"
  #  url = "/photos"
