baseurl = "https://lukewoodsmu.github.io/"
title = "Luke Wood"
theme = "aerial"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  name = "Luke Wood"
  about = 'Software Engineer'
  bg_scroll = ""
  logo = "fa-tree"
  copyright = "Luke Wood"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/lukewoodsmu"

[[params.social]]
  medium = "Stackoverflow"
  icon = "stack-overflow"
  link = "https://stackoverflow.com/users/7159331/luke-wood"

[[params.social]]
  medium = "Resume"
  icon = "file-text"
  link = "/Resume.pdf"

[[params.Projects]]
  name = "Spam Text Classification with a RNN and a MLP"
  icon = "mobile"
  link = "/SpamVsHam.html"

[[params.Projects]]
  name = "Convolutional Neural Net Classification"
  icon = "image"
  link = "/CNNvsMLP.html"

[[params.Projects]]
  name = "UFO Data Visualization"
  icon = "globe"
  link = "/AREA-51"
