baseurl = "https://lukewoodsmu.github.io/"
title = "Luke Wood"
theme = "aerial"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  name = "Luke Wood"
  about = 'Software Engineer'
  bg_scroll = ""
  logo = "fa-tree"
  copyright = "Luke Wood"
  favicon = "/favicon.ico"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/lukewoodsmu"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto::lukewoodcs@gmail.com"

[[params.social]]
  medium = "Resume"
  icon = "file-text"
  link = "/Resume.pdf"

[[params.Projects]]
  name = "Spam Text Classification with a RNN and a MLP"
  icon = "mobile"
  link = "/SpamVsHam.html"

[[params.Projects]]
  name = "Convolutional Neural Net Classification"
  icon = "image"
  link = "/CNNvsMLP.html"

[[params.Projects]]
  name = "UFO Data Visualization"
  icon = "globe"
  link = "/AREA-51"

[[params.OpenSource]]
  name = "Keras Glove"
  icon = "hand-stop-o"
  link = "https://github.com/lukewoodsmu/kerasglove"

[[params.OpenSource]]
  name = "Toast"
  icon = "download"
  link = "https://github.com/lukewoodsmu/toast"

[[params.OpenSource]]
  name = "Parallelized Map Reduce In Browser"
  icon = "desktop"
  link = "https://github.com/LukeWood/ParallelMapReduceInBrowser"
